# Generated by Django 5.1.2 on 2024-10-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='oeuvres/')),
            ],
        ),
    ]
